import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/hero'
import TrustedBy from '@/components/trustedBy'
import Services from '@/components/services'
import AboutUs from '@/components/aboutUs'
import Pricing from '@/components/pricing'
import Faq from '@/components/faq'
import ContactUs from '@/components/contactus'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Hero />
          <TrustedBy />
          <Services />
          <AboutUs />
          <Pricing />
          <Faq />
          <ContactUs />
      </main>
    </>
  )
}
